### ISSUE TITLE
Enlarge the size of the sender picture on the ad search result page

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#261] opened 2017-10-28 19:15 UTC
## Description

On the add search result page, the picture of the sender is displayed too small.
This information will help the traveller to choose which ad to pick.
As our service is based on the trust of the people, and on the community, the information should be highlighted and should take a big place in the ad search.

Enlarge the size of the icon, twice the actual size maybe?

See screenshot below
![image](https://user-images.githubusercontent.com/30872324/32137690-d627126a-bc1c-11e7-9cdb-213e8fd8f716.png)

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by AntonioVdlC** [comment] 2017-10-29 17:25
Instead of increasing the size of the sender info, I have reduced the size of the parcel.
I think that way it looks way better (we'd still have to see what kind of descriptions users put).

**Comment by zuluzaire** [comment] 2017-10-30 22:21
I think the problem is really that we cannot see the content of the user profile picture.
If we can see it, it's like it is useless.
Why are you against the idea of increasing the size of it?

**Comment by AntonioVdlC** [comment] 2017-12-05 08:09
This might have implications on the design of the parcel list element.
Is it still relevant knowing that we have reduced the width of such parcel list elements?

**Comment by AntonioVdlC** [comment] 2017-12-05 08:11
Actually duplicate of #310 😅

**Closed by AntonioVdlC** 2017-12-05 08:11 UTC
Labels: enhancement, M, P2
