### ISSUE TITLE
Add a "Trouver un colis à transporter" button in the header menu

### ISSUE THREAD

**Issue by zuluzaire** [litomba/www#254] opened 2017-10-28 13:16 UTC
## Description

In the header menu add a button "Transporter un colis" or "Trouver un colis à transporter" even when the user is not connected.
Now this button should redirect to the page in the screen below

![image](https://user-images.githubusercontent.com/30872324/32134689-9d0b8e84-bbea-11e7-8354-da742ca55f7b.png)

## Steps to reproduce / User Story

1.
2.
3.
4.

### Operating System

- Android
- iOS
- Windows
- macOS

### Browser

- Chrome
- Firefox
- Safari
- Edge
- Opéra 
- Internet Explorer

**Comment by zuluzaire** [comment] 2017-10-28 13:19
Duplicate

**Comment by AntonioVdlC** [comment] 2017-10-28 22:23
Isn't this a duplicate of #246?
Should I add it here, or on the v1 branch? 😅

**Comment by AntonioVdlC** [comment] 2017-10-28 22:59
Ok, just fixed it here!

**Closed** 2017-10-29 13:38 UTC
Labels: enhancement, P0
